-- Tabla modelos (TypeORM entity Modelo)
CREATE TABLE IF NOT EXISTS modelos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  catalogo VARCHAR(255) NOT NULL UNIQUE,
  familia VARCHAR(255) NOT NULL,
  nomenclatura VARCHAR(255) NOT NULL,
  precio DECIMAL(12, 2) NOT NULL,
  "yearModelo" INTEGER DEFAULT 2026,
  "capacidadCarga" VARCHAR(255),
  "largoChasis" DECIMAL(8, 2),
  "altoCamion" DECIMAL(8, 2),
  "anchoCabina" DECIMAL(8, 2),
  "largoAplicacion" DECIMAL(8, 2),
  "altoAplicacion" DECIMAL(8, 2),
  "anchoAplicacion" DECIMAL(8, 2),
  "distanciaEntreEjes" DECIMAL(8, 2),
  pvb VARCHAR(255),
  motor TEXT,
  tecnologia VARCHAR(255),
  garantia VARCHAR(255),
  equipo TEXT,
  frenos VARCHAR(255),
  hp VARCHAR(255),
  torque VARCHAR(255),
  "kmPorLitro" VARCHAR(255),
  llantas VARCHAR(255),
  "createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
